name: Build and Push Native Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Menambahkan izin agar job bisa menulis ke GHCR
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GraalVM
        uses: graalvm/setup-graal-vm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Kita tidak lagi butuh container build di sini, karena runner GitHub sudah Linux
      - name: Build native executable with Maven
        run: ./mvnw package -Pnative

      # --- LANGKAH BARU 1: Login ke GitHub Container Registry ---
      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- LANGKAH BARU 2: Build dan Push Docker Image ---
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/main/docker/Dockerfile.native # Menggunakan Dockerfile yang sudah ada
          push: true
          tags: ghcr.io/${{ github.repository }}:latest # Menamai image secara dinamis